theme: jekyll-theme-minimal
title: William Daniel Taylor
include: "/images/headshot.JPEG"
description:
  "B.S. Computer Science"

  "B.A. Political Science"

  "Minor in Data Science"

  
  "LinkedIn: https://www.linkedin.com/in/wdtaylor30/"
