theme: jekyll-theme-minimal

title: William Daniel Taylor

author: William Daniel Taylor

avatar: "/images/headshot.JPEG"
  
description:
  "B.S. Computer Science"

navbar-links:
  "LinkedIn: https://www.linkedin.com/in/wdtaylor30/"
